version: "3.8"

services:
  db:
    build: ./db
    container_name: myapp_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: myapp
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: myapp_backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: myapp
      JWT_SECRET: your_jwt_secret
    depends_on:
      - db